version: 2
updates:
  - package-ecosystem: bun
    directory: /
    target-branch: dev
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
    commit-message:
      prefix: chore(deps)
  - package-ecosystem: github-actions
    directory: /
    target-branch: dev
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - "*"
    commit-message:
      prefix: chore(ci)
